[package]
name = "quantum-computer-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.15" # or latest version
rand = "0.8" # for random number generation
egui = "0.15"
plotters = "0.3.1"
image = "0.24.6"
